### ISSUE TITLE
User can disable page menu

### ISSUE THREAD

**Issue by schristodoulou** [johnsonandjohnson/Bodiless-JS#1087]

**Comment by e2thex** [comment]
## Description
As a site editor, I want to mark a page as one that should temporarily not be linked to from any link.

## User Story
AS A site user/content editor,
I WANT the mark a page as not in the menu
SO THAT I can temporarily hide menu items to the page from anywhere on the site.
### Background/Description

### Acceptance Criteria
AC1.
WHEN the user is in the Edit UI and in EDIT mode
THEN there is a "Page" icon in the Admin Menu
AND when the User selects the Page Icon
THEN The sub page menu form panel window opens
AND when the user selects the Disable Page icon
There is an option to disable incoming menu items. as well as disable the whole page
AC2.
When the enable is click the user is presented with the message "..." and the icon changes back to enable icon

AC3. When there is nothing disable the icon change back to not enabled icon

AC4.
If inbound menu items are disabled then 
The static(Preview) site will not render the menu item for any inbound menu items

AC5.
If the Page is fully disabled then 
The static(Preview) site will not render the menu item for any inbound menu items

AC6.
The link will function normally in edit.

### Implementation Notes

**Comment by asiarheyeu** [comment]
Closing as completed
