### ISSUE TITLE
Last typed chars disappear sporadically; some entered data is lost after refreshing a page

### ISSUE THREAD

**Issue by beliayeu** [johnsonandjohnson/Bodiless-JS#14]
## Description

Last typed chars disappear sporadically; some entered data is lost after refreshing a page

### Steps to reproduce

1. open /list page
2. start adding the list items and fill them with text

### Expected result

no content loss happens

### Actual result

last chars in some items are lost after several seconds

## Root cause

* stale data come from Gatsby backend and overwrite client data

##  Background
1. once user makes content changes, browser locks items, to which the user made changes, and sends data to backend. the item is unlocked on timeout. current timeout value is 5 seconds. if user touches an item then lock timeout is reset.
2. backend saves the data from 1. to json files
3. gatsby watches json files and triggers site rebuild once a json file is changes
4. after site is rebuilt, the data is sent back to the client.

issue: the data on  step "4" can be stale. when the data from "4" is delivered to the browser and if the browser already released locks for the items, then the stale data overwrites more recent data. it looks for the user as some characters are disappeared.

## Options how to solve the stale issue
Option 1. Increase item lock timeout.
Option 2.  Do not expire item locks.
Option 3.  Do not refresh with changes made in same browser
Option 4. Verify data before accepting it.
Option 4a. verify data in browser by sending a network request to backend
Option 4b. verify data in gatsby-node.js

## Ideas how to improve simultaneous editing
* we can have a lock for each item on the server side. the client has to acquire the lock in order to make changes for an item. if an item is already locked on the server by a client, then the data originated from other clients is rejected.
* implement [Operational transformation pattern](https://en.wikipedia.org/wiki/Operational_transformation)

**Comment by wodenx** [comment]
Did you post finding’s on the content loss bug somewhere?

Andrei, 11:01 AM
not yet,
in few words - gatsby hmr reload contains stale data, which can override data in browser. our current locking mechanism is not reliable enough, the lock is released for an item if content editor does not touch the corresponding field

at quick glance there are the following approaches
1. disable storage update on hmr
2. implement a page level lock
3. implement revisions for items

11:04 AM
1 and 2 are the sane

Andrei, 11:05 AM
for #2 we can have kind of a manual step required from content editors to start/stop editing

11:06 AM
For 3 we could keep table of revision sha and time stamp and update from hmr only I’d stamp is later?

Andrei, 11:07 AM
the problem with time stamp is that we need to somehow sync client and server time

11:13 AM
Do we? Or just take stamp in client when store is updated and compare to time in client of hmr message or of last update
1 store updated take sha of value and save stamp
2 hmr happens look up sha and see if time is later than last user xhange
Look up sha of incoming value
I me an

Andrei, 11:17 AM
per my understanding there will be issues if 2 clients have different time

11:37 AM
If update comes from another client we discard it

Andrei, 11:41 AM
and what the second client needs to do in order to get latest changes

12:09 PM
Sorry I mean it will be discarded until that field is no longer being wdited
12:15 PM
I mean this issue is related to race condition with content being edited in one browser 
Tbh I still don’t fully understand 
I guess it happens when hmr is triggered by change in one field while change in another field hasn’t been weittev

Andrei, 12:27 PM
browser has data versionN
fs has data versionM
hmr has data versionK

versionK <= versionM <= versionN

hmr inject stale data and if mobx item lock is expired, then it will be replaced with stale data (versionK)

if content editor does not do anything, then it will get versionN in the item

but if content editor focuses the related ui element, then he/she will lock mobx item with overriden stale value and send stale value back to the backend

12:43 PM
M hm 
So issue is really only with stale data from same browser
So if sha doesn’t exist in table, we load it (as long is it’s not locked(

1:03 PM
But we reject it if sha exists and timestamp is old
9:03 PM
had another idea which might be more robust
but involves modifying the data format in the json files
given that the problem is stale data originating in the same browser
what if we add a uuid to each json file uniquely identifying the originating browser (can be created globally on page load)
and just never update an item which originated in the same browser?
