### ISSUE TITLE
Better handling of merge conflicts

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#371]
## User Story
As a content editor
I want to know when my local changes conflict with upstream changes
So I can take appropriate action

## Acceptance Criteria

AC1.
When I execute a pull changes operation
A merge check is made between
- the working tree of the edit environment (EDIT)
- the upstream changeset branch (CHANGESET)
- the production (master) branch. (PRODUCTION)
AND
If there are conflicts between EDIT or CHANGESET and PRODUCTION
Messaging is as per the attached flow.

AC2.
When a merge conflict warning is displayed per the attached flow (message D)
It includes a list of the pages which contain conflicts
AND/OR
If there are conflicts in side-wide data
An indication that conflicts may affect all pages.

AC3.
If the user decides to continue after a merge warning per the attached flow (after message D)
Then all merges are made by resolving conflicts in favor of the lower environment
That is:
- PRODUCTION is merged to CHANGESET resolving conflicts in favor of CHANGESET
- CHANGESET is pulled to EDIT resolving conflicts in favor or EDIT (this is the current behavior)

AC4.
If an error of any kind occurs during any of the server operations (Status Check or Merge)
Then a failure message is displayed

## Technical Notes
- If there are conflicts between CHANGESET and EDIT, but no conflicts with PRODUCTION, then these are resolved silently in favor of EDIT (this is the current behavior)
- Conflicts in non-json files cannot be auto-merged and require a developer.
- As currently, changes which require app restart cannot be pulled automatically.
- Exact messaging is TBD.
- The logic to determine the state should be reusable as it will be leveraged by #439 

[Pull Changes Fkiw.pdf](https://github.com/johnsonandjohnson/Bodiless-JS/files/4918264/Pull.Changes.Fkiw.pdf)

**Comment by wodenx** [comment]
![Uploading IMG_2047 2.jpeg…]()

**Comment by wodenx** [comment]
![Monosnap 2019-07-26 10-55-15](https://user-images.githubusercontent.com/480145/86261073-17f57800-bb8c-11ea-87c8-610d3ba31e12.png)

**Comment by kbray0009** [comment]
A: No changes are available, your Edit Environment is up to date!
B: Changes are available but cannot be pulled, contact your development team for assistance. (code xxxx)
C: Pull success, your Edit Environment is up to date!
D:Your Edit Environment and Changeset differ from production on the following pages: page1name, page2name.
    Do you wish to override Production?
E: Changes are available but cannot be pulled, contact your development team for assistance. (code xxxx)
F: Changes are available but cannot be pulled, contact your development team for assistance. (code xxxx)
G: An error has occurred, please try Pull again in a few minutes. (code xxxx)

Note pagenames are not full URLs.
If User does not want to override production in case of D, how would user reset Edit Environment?  Revert?

**Comment by asiarheyeu** [comment]
Per daily:
- If there are new conflicting updates on prod after last time operator did pull, operator should have two options 1) call developer to resolve conflicts 2) revert to prod
@kbray0009 can you please update requirements and message text accordingly?

**Comment by dewen** [comment]
@kbray0009 please provide message regarding AC2:
```
...
AND/OR
If there are conflicts in side-wide data
An indication that conflicts may affect all pages.
```

**Comment by kbray0009** [comment]
@wodenx @dewen 
"
Changes you have recently made in your Edit Environment conflict with changes that have been made to production since the last time you pulled changes. You can choose to have your changes override the production changes in your changeset, by clicking the check.  Or, you can dismiss this dialogue and contact your development team for assistance. (code xxxx).
"

**Comment by dewen** [comment]
@kbray0009 just to confirm, so we don't provide a list of conflict pages to user.

**Comment by kbray0009** [comment]
@dewen It would be great to do that, but I don't think that's in the requirements.

**Comment by dewen** [comment]
@kbray0009 please check message for (F), should be different from (E)

**Comment by dewen** [comment]
@kbray0009 regarding the site-wide change warning, can you provide the message?

**Comment by kbray0009** [comment]
@dewen 
-Page1
-Page2
-Page3
-A change that affects multiple pages

**Comment by dewen** [comment]
| Code  | Messages |
| ------------- | ------------- |
| A | No changes are available, your Edit Environment is up to date! |
| B | Changes are available but cannot be pulled, contact your development team for assistance. (code 1002) |
| C | Pull success, your Edit Environment is up to date! |
| D | Changes you have recently made in your Edit Environment conflict with changes that have been made to production since the last time you pulled changes. You can choose to have your changes override the production changes in your changeset, by clicking the check. Or, you can dismiss this dialogue and contact your development team for assistance. (code 1004). |
| E | Changes are available but cannot be pulled, contact your development team for assistance. (code 1005) |
| F | Changes are available but cannot be pulled, contact your development team for assistance. (code 1006) |
| G | An error has occurred, please try Pull again in a few minutes. (code 1000) |
