### ISSUE TITLE
Component Form Value does not update when data changes

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#445]
## STR
1. Open the test site home page
2. click on a CTA so that the link button appears
3. Manually edit the json file for that CTA
4. click the link button

## ER
Updated value of link href is displayed in form.

## AR
Original value of link href is displayed in form.

## Notes
This can result in accidentally overwriting a change received from upstream.
The form value is correct after switching the context, but this could be problematic for metatags where the button is in the top context.
Page refresh resets the vqlue.

**Comment by TatsianaMiraniuk** [comment]
Hi @wodenx ,

the bug described by the steps above is not reproduced - the value of a link is updated.

However, there is a case when the value stops being updated. It happens once a user changes a value of the link from UI:
**Steps to reproduce:**
1. Open the test site home page
2. click on a CTA so that the link button appears
3. Manually edit the json file for that CTA
4. click the link button => Updated value of link href is displayed in form (works as expected)
5. update the value of the link (from UI). click V
6. open the corresponding json file. => Json has the new value of the link (works as expected)
7. update the value in the json and save the file
8.  click the link button in UI

**Expected Results**:
Updated value of link href is displayed in form.
**Actual Results:**
the value of the link is not updated in the form




Thanks,
Tatsiana

**Comment by wodenx** [comment]
@TatsianaMiraniuk I believe this is expected behavior related to how quickly you update the json file after the form is saved.  We have [a lock on data in the store after saving](https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/gatsby-theme-bodiless/src/dist/GatsbyMobxStoreItem.ts#L96-L99) in order to mitigate issues in text editors. I can reproduce the problem only if I perform step 7 above immediately after step 5.  If I wait >10s (the duration of the lock), the problem is not reproducible.  cc @beliayeu

**Comment by TatsianaMiraniuk** [comment]
@wodenx , thanks! you're right - confirmed that after waiting for 10s, the content is saved.

**Comment by TatsianaMiraniuk** [comment]
fixed by https://github.com/johnsonandjohnson/Bodiless-JS/pull/519
