### ISSUE TITLE
Better handling for tailwind classes referenced in reusable packages

### ISSUE THREAD

**Issue by wodenx** [johnsonandjohnson/Bodiless-JS#683]
As a site builder I want css purge functionality to happen and not present with issues relying on css precedence for multiples of same classes or order of media queries or order of include of stylesheets. 

## ACS

AC1: bodiless packages (@bodiless/layouts and @bodiless/organisms) have tailwindo configuration and export their tailwind configuration. They do not generate tailwind css files and thus remove purging at package level 
AC2: the tailwind styling from bodiless packages in imported at gatsby-theme-bodiless level, merged.
AC3: There is ability to whitelist packages at site level to prevent purging of packages.  The whitelist list of bodiless packages and is exported from gatsby-theme-bodiless. 
AC4: purge of css happens at site level only 
AC5: feature is implemented on both test site & starter site.
AC6: pr to microlax that applies the changes and process @imodium global brand package.

## Background

There are several bodiless packages which refer to tailwind classes
- bodiless-layouts uses them to set widths
- bodiless-organisms uses them eg for tout layout tokens
- etc...

Further, we expect brand (or other) design libraries to make heavy use of tailwind classes.

Our current methodology is that a package does not export its tailwind config, instead it generates (and purges) whatever css it needs.

Here are the use-cases:
1. package refers to a default tailwind class, and expects a consumer to define the precise meaning of this class (this should be the case for most bodiless packages) 
2. package refers to a *custom* tailwind class, and expects a consumer to define the precise mening of this class (example?)
3. package refers to a  default or custom tailwind class and wants to define the precise meaning of that class (should be rarely true for bodiless packages, but normal for brand design packages)

Specific Proplems
- If a package does not export css for a class, and the class is not used on the site level, it will be purged.
- If a package exports css for a class, it is difficult for site to override that css.  For many classes (which are determinate in nature) this is not a problem, but for some it can be a problem.  In particular, responsive classes (like w-full). Consider:
package:
```
.w-full { width: "100%"; }
```
site:
```
@media (min-width: 768px) {
  .w-full { width: 100% }
}
```

**Comment by hvanyo** [comment]
Paths:
* Namespacing bodiless packages. -- won't solve the problems because if w-full applied to bodiless component, media queries at site level site builder would have to remove w-full.  
* Control Load order of css -- maybe if possible (between site & bodiless) but gets complex with brand be introduced
* Inject in tailwind classes bodiless -- possibility but variant of next one. 
* Do not purge bodiless packages and tailwind config.js and merge into 1 -- complex logic to merge.  -- 
* PRevious method: packages don't generate styles and expect the site to define them.    Need to determine how this works with brand level styles.
* Responsive media queries are important at site level -- need to check -- hacky -- brand css important and site level would need to define new styles and/or then would have ot remove brand ones.
